apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-library-service
  namespace: myflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-library-service
  template:
    metadata:
      labels:
        app: media-library-service
    spec:
      containers:
        - name: media-library-service
          image: thiru98/media-library-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: MEDIA_DATA_DIR
              value: /media
          volumeMounts:
            - name: media-data
              mountPath: /media
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: media-data
          hostPath:
            path: /run/desktop/mnt/host/d/media
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: media-library-service
  namespace: myflix
spec:
  selector:
    app: media-library-service
  ports:
    - port: 8001
      targetPort: 8001
